### ISSUE TITLE
list all included hubot modules in readme

### ISSUE THREAD

**Issue by ycao56** [ibm-cloud-solutions/cloudbot#4]

**Comment by kurtismgit** [comment]
Do we also plan to list the environment variables for each module?  We at least need to mention the minimum set of environment variables needed to make the bot work.  For example, ADAPTER and HUBOT_NAME.  Then provide links to the readme of the enabled external scripts and tell the user to see those readme files for environment variables for each script.

**Comment by ycao56** [comment]
ADAPTER and HUBOT_NAME are mentioned already in current readme. The list being added will also contain the link to each project and ENVs required are supposed to be there.
